name: 'Let Secret Monitor'
description: 'Detect secrets in commits/PRs'

inputs:
  custom_prefix:
    description: '自定义环境变量前缀'
    required: false
    default: 'LetSecret'

runs:
  using: "composite"
  steps:
    - name: Check for secrets
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_PREFIX: ${{ inputs.custom_prefix }}