name: 'Let Secret Monitor'
description: 'Detect secrets in commits/PRs'

inputs:
  custom_prefix:
    description: '自定义环境变量前缀'
    required: false
    default: 'LetSecret'

runs:
  using: "composite"
  steps:
    - name: Secret Detection
      shell: bash
      run: |
        # 原有检测逻辑
        if [ -n "$LEAKED_SECRETS" ]; then
          echo "::error::Found secrets: $LEAKED_SECRETS"
          exit 1
        fi
      env:
        CUSTOM_PREFIX: ${{ inputs.custom_prefix }}

    - name: Post PR Comment
      if: ${{ failure() && github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        script: |
          const message = `⚠️ **安全警报** ⚠️\n检测到以下敏感信息：\n${process.env.LEAKED_SECRETS || '未指定详情'}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })