name: 'Let Secret Detector'
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Secret Detection
        env: 
          COMMIT_SHA: ${{ github.sha }}
          LETSECRET_PASSWORD: "password123"
          LETSECRET_SECRETS: ${{ secrets.LETSECRET_SECRETS }}  # 其实是123456789
        run: |
          source scripts/scanAllFiles.sh


# name: Let Secret Check
# on: [push, pull_request]

# permissions:
#   contents: read
#   issues: write  # 授权Token可写评论

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
        
#       - uses: LetMeFly666/secret-monitor@master
#         with:
#           custom_prefix: "MySecret_"  # 可选自定义前缀
#         env:
#           MySecret_DB_PASSWORD: "password123"        # 文本密钥
#           MySecret_IP_REGEX: |
#             /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/ # 正则表达式