name: Secret Check
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 必须获取前一次提交用于diff
        
      - uses: LetMeFly666/secret-monitor@v1
        with:
          custom_prefix: "MySecret_"  # 可选自定义前缀
        env:
          MySecret_DB_PASSWORD: "password123"        # 文本密钥
          MySecret_IP_REGEX: "/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/" # 正则表达式