# 这是我写的yml，请你帮忙检查其中是否有错误
# 现在先实现一个新开PR，待会儿再实现往已有PR上新增commit
name: PR Commit Info
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Get ALL PR commits (if open/reopen)
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_FULL_NAME=${{ github.repository }}
          echo "PR_NUMBER = $PR_NUMBER"
          echo "REPO_FULL_NAME = $REPO_FULL_NAME"
          COMMITS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER/commits")
          echo "All commits in PR:"
          echo "$COMMITS" | jq '.[].sha'
          echo "$COMMITS" | jq -r '.[].sha' | while read -r sha; do
            echo "Commit SHA: $sha"
          done
      
      - name: Get NEW PR commits (if synchronize)
        if: github.event_name == 'pull_request' && github.event.actionn == 'synchronize'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "NEW PR commit(s) found"


# name: Let Secret Check
# on: [push, pull_request]

# permissions:
#   contents: read
#   issues: write  # 授权Token可写评论

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
        
#       - uses: LetMeFly666/secret-monitor@master
#         with:
#           custom_prefix: "MySecret_"  # 可选自定义前缀
#         env:
#           MySecret_DB_PASSWORD: "password123"        # 文本密钥
#           MySecret_IP_REGEX: |
#             /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/ # 正则表达式