# Github Action中，可以设置PR时触发。但是如果PR后merge前又新增了commit，有没有办法触发？
# Action获取PR的所有commit、获取synchronize时新增的commit
# 这个$GITHUB_TOKEN需要用户设置吗，还是自动就能获取到？
# 这是我写的yml，请你帮忙检查其中是否有错误
name: PR Commit Info
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      -name: Get ALL PR commits (if open/reopen)
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}


# name: Let Secret Check
# on: [push, pull_request]

# permissions:
#   contents: read
#   issues: write  # 授权Token可写评论

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
        
#       - uses: LetMeFly666/secret-monitor@master
#         with:
#           custom_prefix: "MySecret_"  # 可选自定义前缀
#         env:
#           MySecret_DB_PASSWORD: "password123"        # 文本密钥
#           MySecret_IP_REGEX: |
#             /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/ # 正则表达式