# TODO: PR变少了咋办
name: PR Commit Info

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-commits:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get ALL PR commits (if open/reopen)
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_FULL_NAME=${{ github.repository }}
          source scripts/getPrCommits_ALL.sh
      
      - name: Get NEW PR commits (if synchronize)
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_FULL_NAME=${{ github.repository }}
          source scripts/getPrCommits_ALL.sh

          BEFORE_SHA=${{ github.event.before }}
          AFTER_SHA=${{ github.event.after }}
          source scripts/getPrCommits_NEW.sh


# name: Let Secret Check
# on: [push, pull_request]

# permissions:
#   contents: read
#   issues: write  # 授权Token可写评论

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
        
#       - uses: LetMeFly666/secret-monitor@master
#         with:
#           custom_prefix: "MySecret_"  # 可选自定义前缀
#         env:
#           MySecret_DB_PASSWORD: "password123"        # 文本密钥
#           MySecret_IP_REGEX: |
#             /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/ # 正则表达式